### ISSUE TITLE
NetworkExtras : Extension  ByteArray  asIpAddress raises an Error

### ISSUE THREAD

**Issue by gjvanderheiden** [bouraqadi/PharoMisc#2]
Extension is written as follows:

asIpAddress
	NeIpV4Address adoptInstance: self.
	^self

So if you say 
#[200 200 200 0] asIpAdress

The debugger pops up with:
ModificationForbidden: #[200 200 200 0] is read-only, hence its selector primitiveChangeClassTo: cannot be executed with 

Simply replaced it on my image with:

^NeIpV4Address newFrom: self

works fine.

**Comment by gjvanderheiden** [comment]
Installed without anything else on Pharo 10.0

**Comment by bouraqadi** [comment]
Makes sense, since now ByteArray instances are immutable. Integrating your fix @gjvanderheiden. Thanks.
