### ISSUE TITLE
NetworkExtras : tests fail

### ISSUE THREAD

**Issue by gjvanderheiden** [bouraqadi/PharoMisc#4]
Even after fixing the 2 other issues on my local image, some tests fail.

Tested on Pharo 10.0

**Comment by gjvanderheiden** [comment]
NeUdpSendReceiveLargeDataTest  test1Sender1Receiver

sentData := self get100KBytesOfSourceFile **asByteArray**.

asByteArray is missing

**Comment by gjvanderheiden** [comment]
NeUdpUnicastSocketTest testCloseWhileReceiving

not sure what the deal is, because an Error is raised, saying you can't receive on a close socket. Which looks good to me. In other words I would expect that Error, yet the test doesn't expect an Error signaled.

**Comment by bouraqadi** [comment]
Thank you @gjvanderheiden for the issues and the fixes. I'll look at it and fix things.

**Comment by gjvanderheiden** [comment]
Awesome. Using multicast UDP was surprisingly fiddly, not really SmallTalk related.  Your lib toke me to the right direction.

**Comment by bouraqadi** [comment]
Glad it helps 😃

**Comment by bouraqadi** [comment]
Fixed the 2 remaining errors. All tests are green now.
