### ISSUE TITLE
Missing references

### ISSUE THREAD

**Issue by sebastianconcept** [bouraqadi/PharoMisc#5]
Hi @bouraqadi !

I got very curious about 

1. NetworkExtras
2. SimpleMiddleware and
3. CodeMetrics

but in all these it goes to a 404

Any hope of taking a look on these in Pharo 11 or 10?

**Comment by bouraqadi** [comment]
Fixed.  Thank you @sebastianconcept for reporting. 
FYI There were 2 issues:
1. I moved code to the Pharo Folder
2. Links were to ReadMe files in package folders. But, Iceberg deletes anything in code folders and recreate them upon each commit.

**Comment by sebastianconcept** [comment]
@bouraqadi yes Iceberg is not a good team player, it should be disclaimed that it requires to be git exclusive because discovering that is slow and invariably annoying.

Thank you for the push and heads up.

I like a lot `BooleanExpressions`

 I'll be taking a look
